### PR TITLE
Fix several incorrect argument ranks in calls to WRF I/O API routines

### PR DESCRIPTION
**Pull request by mgduda**
This PR corrects the actual argument rank in several calls to WRF I/O API
routines for reading and writing domain time-independent attributes.

### CODE REVIEW

**Comment by mgduda** [comment]
This PR addresses issues pointed out in Issue #163 and in Issue #180.

**Comment by davegill** [comment]
@mgduda 
Michael,

Is there a reason why some of these arrays you went the direction of `(/ var_value /)` and some are `var_value_arr`?

I ask, because likely what you do here we will need to conventionally put into the WRF model, as we have the exact same complaints of argument mismatches with the newer GNU compilers.

**Comment by davegill** [comment]
@mgduda 
Michael,
OK, I got it now.
On "put", you force the input scalar to be an array.
On"get" you store the output variable into an array (which we later pull out index 1.

**Comment by mgduda** [comment]
@davegill The details of the changes are explained in the commit messages:
https://github.com/wrf-model/WPS/pull/184/commits/03e35b60abbec9e06a2617313bcbdc52b14bb353
https://github.com/wrf-model/WPS/pull/184/commits/166c9886fb201865d2b3fd71c6cba22fbe1cde0d

I didn't think the PR description needed to go into such detail, though.

**Comment by davegill** [comment]
@mgduda 
Michael,

I tested the following from inside the standard WRF-system docker container (GNU 9.3.1). This is expected to work since gnu 9 does not make mismatched variables a fatal error.
1. The standard WPS code builds (master branch).
2. This PR's branch (fix_ioapi_put_get_args) builds 

I tested the following with GNU 11.1.0 on cheyenne, where I expected to see an impact.
1. The standard WPS code does not build (master branch) for geogrid, ungrib, or metgrid.
2. This PR's branch (fix_ioapi_put_get_args) builds geogrid.exe and metgrid.exe (what was expected).

**Review by davegill — APPROVED** [review]

**Comment by mgduda** [comment]
@davegill Once this PR has been merged, I was planning to create one more PR for the v4.3.1 release that adds `-fallow-argument-mismatch` to the GNU Fortran flags; that should allow everything to build, but I first wanted to address legitimate issues with subroutine arguments before papering over the remaining errors (e.g., calling `MPI_Bcast` with different argument types, which is completely fine and unavoidable).

**Comment by davegill** [comment]
@mgduda 
Michael, 
I like your 2-PR idea.

**Pull request merged**
