### PR TITLE
Add 'modis_15s_lake' option for LANDUSEF data in GEOGRID.TBL.ARW

### PR DESCRIPTION
**Pull request by mgduda**
This merge adds a new data source, `modis_15s_lake`, for the LANDUSEF
field in the `GEOGRID.TBL.ARW` file. Prepending the selection in the `geog_data_res`
namelist option with 'modis_15s_lake+' will activate the use of this dataset.

Reference for the MODIS 15s dataset (without lake category):
```
 Broxton, P. D., Zeng, X., Sulla-Menashe, D., & Troch, P. A. (2014). A global
 land cover climatology using MODIS data. Journal of Applied Meteorology and
 Climatology, 53(6), 1593-1605. DOI: 10.1175/JAMC-D-13-0270.1
```
The lake category was added by NCAR/MMM.

### CODE REVIEW

**Comment by mgduda** [comment]
@dudhia @barlage @smileMchen Just FYI, this is the PR to include the MODIS 15s dataset with lakes as an option in geogrid.

**Comment by davegill** [comment]
@kkeene44 
Kelly,
Is this dataset available as part of the standard download? 
If so, then:
1. I am OK with this.
2. You may approve.
I assume Michael will merge.

**Comment by weiwangncar** [comment]
Maybe this dataset can be added as an optional download. The data is
already available on Cheyenne.

**Comment by davegill** [comment]
@mgduda @kkeene44 
Folks,
Using Michael's data (abs_path), I did a domain over the Salton Sea. This is an inland water body that is close to the ocean. You can see on the left (4.5 km domain) that the ocean is cat 17 (MODIS) and the lake is 21 (MODIS+LAKES). On the right is the zoomed in Salton Sea. You can see pixels with a 0.5 km resolution.

The geogrid through WRF simulation showed reasonable results for a similar type of domain over Indianapolis (I was looking for lakes, but found urban).

**Comment by davegill** [comment]
Screen Shot 2019-04-12 at 11 43 22 AM

**Comment by mgduda** [comment]
Apparently we need an approving review from someone with write access.
@davegill I'll add you as a reviewer.

**Pull request merged**
