### PR TITLE
Support 9-character variable names in ungrib

### PR DESCRIPTION
**Pull request by mgduda**
This PR enables support for 9-character variable names in ungrib. Prior to the changes in this PR, the variables were only properly handled if their names contained up to 8 characters.

The focus on support for 9 characters (rather than 10, 11, or more) in variable names is justified by the fact that the code to parse Vtables, as well as the intermediate file format, already support 9-character names.

### CODE REVIEW

**Comment by mgduda** [comment]
This PR addresses Issue #215.

**Comment by mgduda** [comment]
As a test of the changes in this PR, I've used the following Vtable:
```
GRIB1| Level| From |  To  | metgrid   | metgrid | metgrid                                 |GRIB2|GRIB2|GRIB2|GRIB2|
Param| Type |Level1|Level2| Name      | Units   | Description                             |Discp|Catgy|Param|Level|
-----+------+------+------+-----------+---------+-----------------------------------------+-----------------------+
  11 | 100  |   *  |      | TT        | K       | Temperature                             |  0  |  0  |  0  | 100 |
  10 | 200  |   *  |      | O3_GFS_DU | Dobson  | Total ozone column                      |  0  | 14  |  0  | 200 |
-----+------+------+------+-----------+---------+-----------------------------------------+-----------------------+
```
Before the changes in this PR, the resulting intermediate files contained only `TT`, and the ungrib inventory trunctated the `O3_GFS_DU` name:
```
PRES   TT       O3_GFS_D
-------------------------------------------------------------------------------
2001.0  O        O          
...
```

After the changes in this PR, intermediate files contain both `TT` and `O3_GFS_DU`, and the ungrib inventory includes all nine characters of the name `O3_GFS_DU`:
```
Inventory for date = 2023-01-05 00:00:00

PRES   TT        O3_GFS_DU
-------------------------------------------------------------------------------
2001.0  O        X      
...
```

**Comment by weiwangncar** [comment]
@jordanschnell Would changing the name of the variable to 8 characters be an alternative?

**Comment by jimbresch** [comment]
@weiwangncar
> Would changing the name of the variable to 8 characters be an alternative?

  Wei, As Michael pointed out, ungrib already supports 9-character variable names. But, not all ungrib routines allow 9-characters. Some use 8-characters. This change make the 9-character length consistent everywhere. I'll approve it as soon as I check that there are no 8-character definitions hiding somewhere.

**Review by jimbresch — APPROVED** [review]

**Review by weiwangncar — APPROVED** [review]

**Review by jordanschnell — APPROVED** [review]
Looks good to me. Thanks, @mgduda

**Pull request merged**
