### PR TITLE
Add new irrigation dataset to GEOGRID.TBL

### PR DESCRIPTION
**Pull request by weiwangncar**
This PR adds a new dataset of irrigation to the table as an optional entry. This dataset is 
0.0833 degree (1/12 degree) resolution, about 9 km. The generated field, named irrigation, is a 2D field of actual percentages (0 - 100). 

In anticipation of other irrigation data sets becoming available, this data is located under 
the generic directory "irrigation" and then in the data-specific "fao" subdirectory.

The data is sourced from 
http://www.fao.org/aquastat/en/geospatial-information/global-maps-irrigated-areas. 

The dataset supports the new WRF model option sf_surf_irr_scheme =1, 2 and 3.

The following image is such a field over CONUS.

irrigation_us

### CODE REVIEW

**Comment by davegill** [comment]
@mgduda @barlage @weiwangncar 
Wei,
Can you plot this irrigation field from the geogrid output for any convenient (non ocean) domain that you have. The WRF registry says that this field is an "irrigated land percentage". We should add a simple description of this field to the PR commit message. Also, is the field really 0-100 (an actual percent) or is it 0-1 (a fraction), for example. 

The WRF registry also has this irrigation information as a 2d array, with no month index. That restriction should also be part of WPS commit message.

**Comment by weiwangncar** [comment]
@barlage Mike, since you have the data under irrigation/fao/, do you expect other sources of data becoming available at some time?

**Comment by barlage** [comment]
Yes, locally we use a much higher resolution 500m dataset over the US, but we are not ready to publish this yet. I feel having an "irrigation/" directory will keep the geog directory more organized.

**Comment by weiwangncar** [comment]
@davegill I've made a plot and updated PR message.

**Comment by weiwangncar** [comment]
@barlage Thanks.

**Comment by davegill** [comment]
@mgduda @jimbresch @weiwangncar 
Michael and Jim,
I am good with this PR.

**Comment by mgduda** [comment]
Do we need to add similar entries to other `GEOGRID.TBL` files, or is `GEOGRID.TBL.ARW` sufficient?

**Comment by weiwangncar** [comment]
@mgduda I know we don't need to add it for NMM, FIRE, noahmp, but iffy for chem.

**Comment by davegill** [comment]
@mgduda 
Michael,
I would just make the minimum change, and only do the single file GEOGRID.TBL.ARW. The chemistry group is unlikely to be interested in this capability.

**Comment by weiwangncar** [comment]
@mgduda @davegill Thanks. Shall I merge or would one of you do so?

**Comment by mgduda** [comment]
I'll merge this soon. I'm running a couple of final tests.

**Comment by weiwangncar** [comment]
@mgduda Thanks.

**Comment by davegill** [comment]
@mgduda 
Michael,
Wei manufactured some metgrid files for me which included the irrigation variables. I used those metgrid files in a few regression tests in the WRF model to test the irrigation PRs wrf-model/WRF#980 and wrf-model/WRF#1149.

**Pull request merged**
