### PR TITLE
Noahmp dyamic irrigation

### PR DESCRIPTION
**Pull request by prasanthvkrishna**
This is for the new dynamic irrigation scheme implemented in Noah-MP (WRF Pull request #1372).  

File changed : GEOGRID.TBL.ARW.noahmp

New static variables are 1. Irrigation fraction (IRFRAT), 2. Sprinkler irrigation fraction (SIFRACT), Micro-irrigation fraction (MIFRACT), and 3. Flood irrigation fraction (FIFRACT).

Please see this for documentation: https://drive.google.com/file/d/1dfBUMIzhi9QxNNUJ7P3wnWIzS_4TjMCx/view?usp=sharing

WPS Geog data for the dynamic irrigation scheme: /glade/work/prasanth/AG_GEOG

### CODE REVIEW

**Review by andrewsoong — COMMENTED** [review]
How to get crop irrigation_map sprinkler_fra and micro_fra snd flood_fra ？

**Comment by prasanthvkrishna** [comment]
> How to get crop irrigation_map sprinkler_fra and micro_fra snd flood_fra ？

All the WPS data are provided here,
WPS Geog data for the dynamic irrigation scheme: /glade/work/prasanth/AG_GEOG

**Comment by andrewsoong** [comment]
I mean how to download crop irrigation_map sprinkler_fra and micro_fra snd flood_fra by users，is there any other way to get? I am not a NCAR user，Thanks!

**Comment by davegill** [comment]
@andrewsoong @prasanthvkrishna @kkeene44 @mgduda
> I mean how to download crop irrigation_map sprinkler_fra and micro_fra snd flood_fra by users，is there any other way to get? I am not a NCAR user，Thanks!

Prasanth,
Thank you for making this data available to us.

Andrew,
For the upcoming release, we will update our web page of static geogrid input to include this data set.

**Comment by mgduda** [comment]
@prasanthvkrishna The `/glade/work/prasanth/AG_GEOG` directory on Cheyenne isn't readable by others. Could you add read permissions so that I can test this PR with the new datasets?

**Comment by prasanthvkrishna** [comment]
> @prasanthvkrishna The `/glade/work/prasanth/AG_GEOG` directory on Cheyenne isn't readable by others. Could you add read permissions so that I can test this PR with the new datasets?

@mgduda Please try now. I have changed the permission.

**Comment by mgduda** [comment]
@prasanthvkrishna Thanks for the quick response! I've been able to copy and unpack the datasets for testing.

**Comment by mgduda** [comment]
@prasanthvkrishna This isn't an issue with this PR, per se, but I did notice that the `units` and `description` for the `IRFRACT` field seemed inconsistent with the three other fields being added in this PR. For example, the units for IRFRACT are "Irrigation", the description says "IRRIGATED AREA", while the field appears to be something like a fraction.

```
	float IRFRACT(Time, south_north, west_east) ;
		IRFRACT:FieldType = 104 ;
		IRFRACT:MemoryOrder = "XY " ;
		IRFRACT:units = "Irrigation" ;
		IRFRACT:description = "IRRIGATED AREA" ;
		IRFRACT:stagger = "M" ;
		IRFRACT:sr_x = 1 ;
		IRFRACT:sr_y = 1 ;
```

**Comment by prasanthvkrishna** [comment]
> @prasanthvkrishna This isn't an issue with this PR, per se, but I did notice that the `units` and `description` for the `IRFRACT` field seemed inconsistent with the three other fields being added in this PR. For example, the units for IRFRACT are "Irrigation", the description says "IRRIGATED AREA", while the field appears to be something like a fraction.
> 
> ```
> 	float IRFRACT(Time, south_north, west_east) ;
> 		IRFRACT:FieldType = 104 ;
> 		IRFRACT:MemoryOrder = "XY " ;
> 		IRFRACT:units = "Irrigation" ;
> 		IRFRACT:description = "IRRIGATED AREA" ;
> 		IRFRACT:stagger = "M" ;
> 		IRFRACT:sr_x = 1 ;
> 		IRFRACT:sr_y = 1 ;
> ```

@mgduda Could you please edit it as below?
units="fraction"
description="Irrigation area fraction"
Thanks

**Comment by mgduda** [comment]
@prasanthvkrishna If you've already handed off the datasets to the WRF group, we should contact one of them to make the changes to "units" and "description" in the copy that they intend to distribute; otherwise, I think it would be best for you to make the change in your copy of the dataset. I only made copies to my desktop machine for testing, but I don't have the ability to update any "official" copies of these files.

**Comment by prasanthvkrishna** [comment]
> @prasanthvkrishna If you've already handed off the datasets to the WRF group, we should contact one of them to make the changes to "units" and "description" in the copy that they intend to distribute; otherwise, I think it would be best for you to make the change in your copy of the dataset. I only made copies to my desktop machine for testing, but I don't have the ability to update any "official" copies of these files.

Thanks @mgduda I will update the files on my glade.  I will inform the WRF group about this.

**Comment by prasanthvkrishna** [comment]
> > @prasanthvkrishna If you've already handed off the datasets to the WRF group, we should contact one of them to make the changes to "units" and "description" in the copy that they intend to distribute; otherwise, I think it would be best for you to make the change in your copy of the dataset. I only made copies to my desktop machine for testing, but I don't have the ability to update any "official" copies of these files.
> 
> Thanks @mgduda I will update the files on my glade. I will inform the WRF group about this.

@davegill @weiwangncar @mgduda I have updated the irrigation geog files and saved under /glade/work/prasanth/AG_GEOG Please let me know if you have any questions.

**Comment by weiwangncar** [comment]
@prasanthvkrishna I see that we already have irrigation data in /glade/work/wrfhelp/WPS_GEOG/crop/ directory. Are you suggesting that we should update them with your new tar files?

**Comment by prasanthvkrishna** [comment]
> @prasanthvkrishna I see that we already have irrigation data in /glade/work/wrfhelp/WPS_GEOG/crop/ directory. Are you suggesting that we should update them with your new tar files?

@weiwangncar Yes, Wei. The existing one is my previous version. In the updated version, I have corrected the units and name of the variables to 'fraction' in the index file. So please replace the file.

**Comment by weiwangncar** [comment]
@prasanthvkrishna I've done that. Would you like to try to use data from that directory as a test? Thanks.

**Review by mgduda — APPROVED** [review]

**Pull request merged**
