### PR TITLE
Adding entries to the Metgrid table for MAD-WRF

### PR DESCRIPTION
**Pull request by pedro-jm**
MAD-WRF requires the following entries in the metgrid table. The variables are optional and can be used to improve the cloud analysis in Real.

### CODE REVIEW

**Comment by pedro-jm** [comment]
@mgduda @dudhia 
I am wondering if it would be possible to add this update to the Metgrid table sooner than WPS version 4.5 since that requires waiting pretty much a whole year. The change in the Metgrid table is unlikely to have side effect on WPS users, but not having the update has a major impact on MAD-WRF users.

**Comment by weiwangncar** [comment]
@pedro-jm We can try 4.4.1.

**Comment by pedro-jm** [comment]
@weiwangncar 
That would be good, thanks.

**Comment by weiwangncar** [comment]
@mgduda Would you have time to make this part of 4.4.1 release?

**Review by mgduda — APPROVED** [review]
@pedro-jm Apologies for the long delay in getting to this PR!

**Pull request merged**
