### PR TITLE
Add 20 new gwd fields

### PR DESCRIPTION
**Pull request by weiwangncar**
The new gravity wave drag option to be released with WRF v4.3 (gwd_opt = 3) requires 20 new input fields for VAR, CON, OA1-4, OL1-4. These are added to GEOGRID.TBL.ARW. The source of these fields is from GMTED2010 30-arc-second topography.

The first group of data is similar to those required for gwd_opt = 1, but with slight different processing (i.e. removing de-trending applied). The second group of data is new and needed to account for small-scale GWD and turbulent orographic form drag.

The data is contributed by Mike Toy of NOAA/GSL.

### CODE REVIEW

**Comment by mgduda** [comment]
@weiwangncar Could you clarify the intent of the new `geogrid/GEOGRID.TBL.ARW_gwd-opt3` file, given that the entries have already been appended to the `GEOGRID.TBL.ARW` file?

**Comment by weiwangncar** [comment]
@mgduda That file should not be there. I've deleted now.

**Comment by mgduda** [comment]
@weiwangncar Can you squash the four commits in this PR into one? If you aren't familiar with the process of doing this with an interactive rebase, just let me know and I can help.

**Comment by weiwangncar** [comment]
@mgduda Let me know if I should do more on this PR...

**Comment by mgduda** [comment]
@weiwangncar if you don't have any objections, I can fix up the commit history of this branch, then force-push the changes to your fork before reviewing.

**Comment by weiwangncar** [comment]
@mgduda Please go ahead. Let me know if I did something wrong here.

**Comment by mgduda** [comment]
@weiwangncar It's not wrong, but the merge of `master` onto your branch in 9333b76 is unnecessary.

**Comment by weiwangncar** [comment]
@mgduda Thanks. I realized that after I did it...

**Review by mgduda — APPROVED** [review]

**Pull request merged**
