### PR TITLE
Modifying METGRID.TBL.ARW for WRF PR #1567

### PR DESCRIPTION
**Pull request by twjuliano**
This PR complements WRF PR #1567 (https://github.com/wrf-model/WRF/pull/1567) and #1616 (https://github.com/wrf-model/WRF/pull/1616) in order to clean
the logic in dyn_em/module_initialize_real, enable more flexibility when pre-processing first guess aerosol fields (e.g., GEOS-5) for the Thompson Aerosol-Aware scheme (mp_physics=28), and handle processing of black carbon aerosol and biomass burning emissions.

Here is the text taken from WRF PR #1567:
Modifications have been made to the METGRID.TBL file to simplify the subsequent logic in the real program's dyn_em/module_initialize_real. Specifically, we: 
   * replace FLAG_QNWFA and FLAG_QNIFA with FLAG_QNWFA_CL and FLAG_QNIFA_CL, respectively, in the W_WIF_DEC and I_WIF_DEC entries, where “CL” stands for climatology; 
   * add FLAG_QNWFA and FLAG_QNIFA to the QNWFA and QNIFA entries, respectively, for the first guess aerosol arrays;
   * add entry P_WIF to give the user the option to interpolate the first guess aerosol using the native pressure levels of the host model;
   * use num_wif_levels for any z dimension associated with the aerosol field entries (climatology or first guess);
   * add surface aerosol emission arrays QNWFA2D and QNIFA2D to be processed.

Here is the text taken from WRF PR #1616
We add entries to METGRID.TBL to handle the black carbon aerosol category in addition to biomass burning emissions. Specifically, we:
   * add monthly climatology entries for black carbon aerosol (B_WIF_*) which generate FLAG_QNBCA_CL for processing in real
   * add first guess entry for black carbon aerosol (QNBCA) which generates FLAG_QNBCA for processing in real
   * add first guess entry for anthropogenic emission of black carbon aerosol (QNBCA2D) which generates FLAG_QNBCA2D
   * add first guess entries for biomass burning emissions of organic carbon (QNOCBB2D) and black carbon (QNBCBB2D) which generate FLAG_QNOCBB2D and FLAG_QNBCBB2D, respectively

Note that the new .dat file for monthly GOCART climatology is hosted on Google Drive: https://drive.google.com/file/d/1BYflyu65kP5giRYbTzKo6y4iSnTfb1Fw/view?usp=sharing

### CODE REVIEW

**Comment by twjuliano** [comment]
Tagging @davegill so he is aware of this PR

**Comment by weiwangncar** [comment]
@twjuliano Where do the two surface emission fields come from? Do they come from some grib data source? Should they be added to any of the existing Vtables or should a new Vtable be added?

**Comment by twjuliano** [comment]
> @twjuliano Where do the two surface emission fields come from? Do they come from some grib data source? Should they be added to any of the existing Vtables or should a new Vtable be added?

@weiwangncar The two surface emission fields come from the host model for the first guess aerosol. For instance, we have been using GEOS-5 to provide the surface emissions. The data are written to WPS intermediate files and then processed during metgrid using the fg_name entry in namelist.wps. We will provide the code to generate the WPS intermediate files so that this is simplified for anyone interested in using GEOS-5 aerosol forcing or adapting the code for other host models. Hopefully this helps, thanks.

**Comment by weiwangncar** [comment]
@twjuliano Thanks. So the data from GEO-5 is in netCDF format?

**Comment by twjuliano** [comment]
> @twjuliano Thanks. So the data from GEO-5 is in netCDF format?

@weiwangncar Yes, exactly. We pull the GEOS-5 netCDF files from NASA and then convert them to WPS intermediate.

**Comment by mgduda** [comment]
@twjuliano The title and description of this PR are probably not as clean and direct as they could be in explaining the purpose and effect of this PR. Since the commit messages for individual commits in a PR will be preserved, could you also provide a useful commit message? Additionally, it's customary to use branch names that are in some way indicative of the contents of the branch, since the branch name does appear in the git history; e.g.:
```
Merge branch 'hide_NO_GRIB2_opts' into develop
```
Overall, it might be worth incorporating your changes into a new branch with an appropriate name and using a more descriptive commit message, and opening a new PR from that branch.

If it would be helpful, I could point you to some other WPS PRs that I think serve as good examples. I apologize that we don't have documentation for contributors to the WPS that would explain what we generally expect; this is definitely something that we'd like to have sometime in future.

**Comment by mgduda** [comment]
Superseded by PR #201 .

**Pull request closed without merging**
