### PR TITLE
Add new tile drainage map TD_FRACTION to GEOGRID.TBL.ARW.noahmp

### PR DESCRIPTION
**Pull request by prasanthvkrishna**
**Abstract**: The purpose of this PR is to support the Noah-MP tile drainage scheme with 30 Arc Second CONUS tile drainage map. 

**File Changed** : geogrid/GEOGRID.TBL.ARW.noahmp. Updated with TD_FRACTION field ( priority=1;  optional=yes).

**Reference for TD_FRACTION map**: 
_Valayamkunnath, P., Barlage, M., Chen, F., Gochis, D. J., & Franz, K. J. (2020). Mapping of 30-meter resolution tile-drained croplands using a geospatial modeling approach. Scientific data, 7(1), 1-10._

**Test conducted**: Test conducted on Cheyenne for a CONUS 4-km domain (Generated geo_em_d01.nc with TD_FRACTION map).

**Compiler used**: intel/19.1.1, netcdf/4.8.1

**Tile Drainage Data (WPS format) (for the US only)**: /glade/work/prasanth/AG_GEOG/tile_drainage_map.tar.gz

### CODE REVIEW

**Comment by mgduda** [comment]
Is the new `TD_FRACTION` field something that is required in the WRF/WPS v4.4 release to support other NoahMP changes that will also appear in WRF v4.4? Or is the `TD_FRACTION` field currently only used in development versions of NoahMP that will appear in a future (later than v4.4) WRF release?

**Comment by prasanthvkrishna** [comment]
> Is the new `TD_FRACTION` field something that is required in the WRF/WPS v4.4 release to support other NoahMP changes that will also appear in WRF v4.4? Or is the `TD_FRACTION` field currently only used in development versions of NoahMP that will appear in a future (later than v4.4) WRF release?

@mgduda This is for the new Noah-MP tile drainage scheme in the WRF/WPS v4.4 release.

**Comment by mgduda** [comment]
@prasanthvkrishna Thanks -- I've switched the base of this PR to the 'develop' branch in this case. We'll be creating the WPS `release-v4.4` branch from `develop` soon.

**Comment by prasanthvkrishna** [comment]
> @prasanthvkrishna Thanks -- I've switched the base of this PR to the 'develop' branch in this case. We'll be creating the WPS `release-v4.4` branch from `develop` soon.

@mgduda Thank you.

**Comment by weiwangncar** [comment]
@prasanthvkrishna When you are ready, please let us know where we can obtain the data (e.g. from Cheyenne).

**Comment by prasanthvkrishna** [comment]
> @prasanthvkrishna When you are ready, please let us know where we can obtain the data (e.g. from Cheyenne).

@weiwangncar The data is ready. Please find it here: "/glade/work/prasanth/AG_GEOG/tile_drainage_map.tar.gz"

**Comment by weiwangncar** [comment]
@prasanthvkrishna Would it be better to just name it 'drainage_map'? I see that in the crop/ directory, you have irrigation_map/ subdirectory.

**Comment by weiwangncar** [comment]
@prasanthvkrishna Thanks. You will need to change it too in the GEOGRID.TBL.ARW.noahmp.

**Comment by prasanthvkrishna** [comment]
> @prasanthvkrishna Thanks. You will need to change it too in the GEOGRID.TBL.ARW.noahmp.

@weiwangncar I have updated the GEOGRID.TBL.ARW.noahmp.

**Comment by weiwangncar** [comment]
@prasanthvkrishna That's great. I have placed the data in the normal WPS location on Cheyenne: /glade/work/wrfhelp/WPS_GEOG/.

**Comment by prasanthvkrishna** [comment]
> @prasanthvkrishna That's great. I have placed the data in the normal WPS location on Cheyenne: /glade/work/wrfhelp/WPS_GEOG/.

@weiwangncar Thanks, Wei.

**Comment by mgduda** [comment]
@prasanthvkrishna The title and description of this PR are probably not as useful as they could be in explaining the purpose and effect of this PR. Could you modify the title to describe in a short, single line what this PR accomplishes. And could you update the description to include more details? For example, what new field is added? Is the field optional or required? Can you include any details about the dataset itself (e.g., is there a reference in the literature for the dataset)?

**Review by mgduda — CHANGES_REQUESTED** [review]
The title and description of this PR are probably not as useful as they could be in explaining the purpose and effect of this PR. Could you modify the title to describe in a short, single line what this PR accomplishes. And could you update the description to include more details? For example, what new field is added? Is the field optional or required? Can you include any details about the dataset itself (e.g., is there a reference in the literature for the dataset)?

**Comment by prasanthvkrishna** [comment]
> Is the new `TD_FRACTION` field something that is required in the WRF/WPS v4.4 release to support other NoahMP changes that will also appear in WRF v4.4? Or is the `TD_FRACTION` field currently only used in development versions of NoahMP that will appear in a future (later than v4.4) WRF release?

@mgduda Yes, this PR is for the current WRF release.

**Comment by mgduda** [comment]
> > Is the new `TD_FRACTION` field something that is required in the WRF/WPS v4.4 release to support other NoahMP changes that will also appear in WRF v4.4? Or is the `TD_FRACTION` field currently only used in development versions of NoahMP that will appear in a future (later than v4.4) WRF release?
> 
> @mgduda Sorry for the delay. I have updated the PR description. Please review and let me know.

@prasanthvkrishna No worries at all about the delay, and thanks for providing a nice description of this PR!

**Review by mgduda — APPROVED** [review]

**Pull request merged**
